# 中间件全局错误处理

```js
const catchError = async(ctx,next)=>{
        try{
            await next()
        }catch(error){
            const isDev = global.configs.environment === 'dev'

            const isHttpException = error instanceof global.errs.HttpException
            console.log(isHttpException)
            if(isDev && !isHttpException){
                throw error
            }
            if(isHttpException){
                ctx.body = {
                    msg : error.msg,
                    errorCode : error.errCode,
                    requestUrl: `${ctx.method} ${ctx.path}` 
                }
                ctx.status = error.code
            }else{
                ctx.body = {
                    msg : "对不起，我们错了。",
                    errorCode : 9999,
                    requestUrl: `${ctx.method} ${ctx.path}` 
                }
                ctx.status = 500
            }
        }
}

module.exports = {catchError}
```

