从头屡一下异步函数的解决方案

# iterator

首先从Symbol，Symbol是一个对象的新属性，该属性上部署了很多默认接口，有很多特殊功能，其中之一便是遍历器Iterator，iterator是用于遍历数据结构的遍历器，其原理大概为

```js
function iterator(arr){
        let currentIndex = 0
        return  {
            next(){
                return currentIndex<arr.length? {value:arr[currentIndex++] ,status:false} : {value:undefined,status:true}
        }
    }
}
let arr = [1,5,7,8,4,1]
let itr = iterator(arr)
itr.next()
```

其应用比如for of 循环遍历，遍历到最后会识别status的状态值来结束遍历。

# Generator

现在有了iterator的基础我们来看Generator遍历器接口生成器。Generator生成器为其中的语句提部署了iterator接口，每一次调用next，语句就会向下执行一个yeild

```js
function* generator(){
    yield 1
    yield 2
    yield 3
    yield 4
}
let obj = {}
obj[Symbol.iterator] = generator
for(let item of obj){console.log(item)}
```

生成器本来的作用是为对象添加Symbol[iterator]接口只是现在被强行用来解决异步问题。

yield是产出的意思，因为不是为异步编程而设计，所以每一次让异步函数向下执行，还是要去手动添加语句，.next(),

```js
    $(function(){
        function getNews(){
                setTimeout(function(){
                    console.log("第一个定时器结束")
                    let url = "第二个定时器结束"
                    GM.next(url)
                },1000)
                //这里如果不是一个异步的任务就会报Generator is running！的错误。
        }

        function getCmt(url){
            setTimeout(function(){
                    console.log(url)
            },1000)
        }

        function* getMsg(){
            console.log("请求文章")
            let url = yield getNews()
            console.log("请求评论")
            yield getCmt(url)
        }

        let GM = getMsg()
        
        $("button").click(()=>{
            G.next()
        })
    })
```

因为其内部包含的语句体一般为异步请求语句，所以一般要将返回值传入下一个yield里面，所以GM.next一般就要写在第一个yield函数中，那么其就必须被包含在一个异步的函数中，不然就会报Generator is running！的错误，就是在第一个yield还没结束就掉用另一个。

同时还要注意传值问题，GM.next会返回一个json,注意每一次调用next并不会执行，而只会读，所以函数在扔到yield里面的时候要先调用好。

```js
{
    value:funciton(){
        console.log(1)
        }(), 
    status:false
}
```

可以看出来yield起的是阻塞而不是读取的作用。

传参因为其内部包含的语句体一般为异步请求语句，所以一般要将返回值传入下一个yield里面，所以GM.next一般就要写在第一个yield函数中，于是就想下面这样传值：

```js
function* getMsg(){
    let url = yield getNews()	//1
}
getMsg().next(1)
```

可是我们的语句不都是异步的，于是我们就要使用new Promise函数返回一个异步函数。

# promise

所以我们先来了解一下promise函数，promise表示未来一段时间会发生的事，我们可以再里面写同步的语句也可以写异步的语句，但是同步的语句只是在定义上被包裹成了异步，但是实际的执行效果还是同步

```js
let promise = new Promise(function(resolve,reject){
        setTimeout(function(){
              reject('no')
      	      resolve("loveEnd")
        },1000)
    })
    promise.then((data)=>{
        console.log(data)
    },(err)=>{
        console.log(err)
    })
	promise.then(data=>console.log(data))
	promise.catch(error=>console.log(error))
```

那么接下来我们就可以来结合两者了，Generator的yield需要一个异步的语句，那么promise就给他异步语句，

可是要我们自己去判断promise的结束还是太麻烦，于是在node之中出现了co这么一个库，他可以自动化的执行Generator的promise语句体。

```js
let co =require("co")
let fetch = require("node-fetch")

co(function* (){
        let res = yield fetch("https://api.github.com/users/chrissycoyier/repos")
        
        let resJson = yield res.json()

        console.log(resJson)
})
```

这段代码其实暗藏玄机，首先看第一个yield，他存在的意义是接受fetch函数暴露的返回值。第二个才是阻塞执行，当fetch内部执行到resolve的时候，co自动调用next并且传入res，当一切返回妥当时，解开第二层阻塞。

那么我们来推理一下co库到底是什么原理呢，首先从其存在意义出发，co库用来解决GM.next嵌套问题，co库会识别某一个特定的点，然后自动调用next，那么这个点是？看以下代码。

# GO

```js
co(function* (){
        let tryy = yield new Promise(resolve=>{
            setTimeout(()=>{
                    resolve(1111)
            },1000)
        })
        console.log(tryy)		//1111
})
function* G(){
    let tryy = yield new Promise(resolve=>{
        setTimeout(()=>{
                resolve(1111)
        },1000)
    })
    console.log(tryy)		//undefined
}
let g = G()
g.next()
g.next()

```

从传值来看便真相大白，他识别的是resolve和reject传的值然后自动的补一个next，来达到自动执行。

那么Generator已经结束了，我们来看看async函数。忽略掉兼容问题他是我们目前最好的易步解决方案。

# async

> 有await表达式的函数没有async关键字会报错
>
> 有await表达式的函数没有async关键字会报错
>
> 有await表达式的函数没有async关键字会报错

重要的事情说三遍。

通常为async和await连用

对于async，他包装过的函数会被返回为一个异步函数，当然和promise一样可能会没有实际效果。

```js
async function count(){
	return function(){console.log(1)}
}
console.log(count())
VM171:4 Promise {<resolved>: ƒ}
```

**被async包装的函数分为两种**

有await的函数，以及只有async的异步函数

**有await的函数**

我们回想一下和async很像的generator遍历器，我们想在yield关键字后的语句之间传值，就需要利用next传参，而await就解决了这个问题

```js
async function init(){
    let data = await helloWorld()
    console.log(data)
    let ses = await read()
    console.log(ses)
    await console.log("ss")
    let time = await timer()
    console.log(time)
}
```

await关键字其实是一个求值表达式，他能够将promise对象的返回值（promise语句里面用resolve函数传值和用return是一个效果的）里面的value捕获出来作为所得值，同时它还能判断async语句的执行结束与否，以及阻塞语句执行。

内部函数（一、同步的内部函数）

```js
async function helloWorld() {
    console.log(1)
    return 'hello world' || throw(Error())
}
```

使用return或者是throw向下传值

内部函数（二、异步的内部函数）

async function调用后会返回一个promise，await接受一个promise，并把promise resolved的值作为await表达式的值。

```js
async function read(){
    return new Promise(resolve=>{
        fs.readFile("./cot.txt",(err,data)=>{
            let dataset = data.toString()
            // console.log(data.toString())
             resolve(data.toString())
            // resolve(dataset)
        })
    })
}
```

```js
function timer(){
    return new Promise(resolve=>{
        setTimeout(function(){
            resolve(1)
        },2000)
    })
}
```

使用promise传值。

#  util.promisify

Node.js中的回调函数，根据约定具有统一形式，`(err, value)=>{}`，
因此，我们可以用统一的办法，将接受这种回调函数作为参数的函数，转换为返回promise的函数，
Node.js v8.0.0版本增加了`util.promisify`函数，用以实现这个功能

```js
const { promisify } = require('util');
使用结构赋值的方式拆解util类，但是这里还是运行时获取，不如import静态获取。
const readFileAsync = promisify(fs.readFile);
将readfile转换为规定的回调格式。
```

这样readFile的回调函数参数就转换为promise型的了，会自动传参。

```js
readFile('./index.js', 'utf8')
    .then((text) => {
        console.log(text);
    })
    .catch((err) => {
        console.log('Error', err);
    });
```

和async配合

```js
async function doFile() {
    try {
        const text = await readFile('./index.js', 'utf8');
        console.log(text);
    } catch (err) {
        console.log('Error', err);
    }
}
doFile();
```

没错也就是说readfile在转换之后会默认resolve一个data、reject一个error，data接收掉然后操作，error直接catch掉

```js
readFileAsync('./cot.txt').then(data=>data.toString()).then(console.log)

let pro = new Promise(resolve=>resolve("1111"))
pro.then(console.log)
```

额我也不懂为什么，反正这么写起来好暴力呀。	

# Fetch

<https://www.cnblogs.com/libin-1/p/6853677.html>